spring:
  datasource:
    url: jdbc:postgresql://server_staging:5432/postgres
    username: postgres
    password: postgres_demo
  redis:
    host: redis_staging
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO